# Generated by Django 4.2 on 2025-06-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desctiption',
            new_name='description',
        ),
    ]
